### ISSUE TITLE
PlayIn Background feature

### ISSUE THREAD

**Issue by floelm** [aws/amazon-ivs-react-native-player#68]
**Feature**
Hi,
it would be nice to have a flag which enables that the stream continues when the app is put to the background (audio only then) similar to react-native-video's feature described here: https://github.com/react-native-video/react-native-video#playinbackground

Thanks for working on this project :)

**Comment by maxstoller** [comment]
Hi @floelm, we're looking into this and will get back to you here. Thanks!

**Comment by maxstoller** [comment]
The SDK currently pauses the player when the app is backgrounded. e.g: https://github.com/aws/amazon-ivs-react-native-player/blob/f541551ef11acad714e7f2613b26b0487ae356db/ios/AmazonIvsView.swift#L268-L271

We are evaluating removing this code in a future release so that developers can control the background behavior themselves at the application level. We will let you know if/when we release that change.

Thanks for the feedback.
